# Generated by Django 2.1.4 on 2019-03-08 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Artiste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('image', models.ImageField(default='default.jpg', null=True, upload_to='artiste_punchline_image')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auteur', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('date_comment', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Punchline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punchline_contenu', models.CharField(max_length=250)),
                ('date_poste', models.DateTimeField(default=django.utils.timezone.now)),
                ('poster_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rappeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='punchline.Artiste')),
                ('rappeur_album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='punchline.Album')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='punchline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='punchline.Punchline'),
        ),
    ]
