# Generated by Django 2.1.4 on 2019-03-09 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('punchline', '0002_auto_20190309_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='punchline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='punchline.Punchline'),
        ),
    ]
